name = "cf-worker-social-pawsitiv-space-s3"
main = "src/index.js"
compatibility_date = "2023-01-27"
type = "webpack"

workers_dev = true

[vars]
AWS_DEFAULT_REGION = "us-east-005"
AWS_S3_BUCKET = "social-pawsitiv-space.s3.us-east-005.backblazeb2.com"

[env.prod]
workers_dev = false

[env.prod.vars]
AWS_DEFAULT_REGION = "us-east-005"
AWS_S3_BUCKET = "social-pawsitiv-space.s3.us-east-005.backblazeb2.com"

[[env.prod.routes]]
pattern = "media.pawsitiv.space"
custom_domain = true
